# Generated by Django 5.2.2 on 2025-06-11 03:47

import music_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=music_api.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
