# Generated by Django 5.2.2 on 2025-06-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='vote_to_skip',
            new_name='votes_to_skip',
        ),
    ]
